### ISSUE TITLE
Nonce doesn't change when generating small random integers

### ISSUE THREAD

**Issue by proto-n** [paragonie/seedspring#2]
When generating integers within a small range (less than 64), the nonce for the getBytes function doesn't change, thus the generation tends to fail often (since it repeatedly generates the same int, which may not be in the desired range).

Example faulty behavior:

```
$prng = new \ParagonIE\SeedSpring\SeedSpring('JuxJ1XLnBKk7gPAS');
$int = $prng->getInt(0,19);
```

> PHP Fatal error:  Uncaught Exception: RNG is broken - too many rejections in .../src/SeedSpring.php:176

```
$prng = new \ParagonIE\SeedSpring\SeedSpring('JuxJ1XLnBKk7gPAS');
$int = $prng->getInt(0,20);
```

> PHP Fatal error:  Uncaught Exception: RNG is broken - too many rejections in .../src/SeedSpring.php:176

 etc.

The reason for this is the following: `getNonce` gets the number random bytes to be generated in the `$increment` parameter. It then uses this parameter to increase the internal counter the following way:

```
$incr = (int) \floor(($increment + ($increment % 16)) / 16);
$this->counter += $incr;
```

Obvously, when this parameter is `$increment==1` (as it is, in the cases above), the counter doesn't get incresed (`$incr == 0`).

Question: what is the reasoning behind the way the counter is increased right now? Wouldn't 

```
$this->counter+=1
```

be theoretically sufficient?

**Comment by proto-n** [comment]
This of course also means that when generating `1` random byte repeatedly, the same byte is generated ad infinitum:

```
$prng = new \ParagonIE\SeedSpring\SeedSpring('JuxJ1XLnBKk7gPAS');
$byte = $prng->getBytes(1);
print ord($byte)."\n";
$byte = $prng->getBytes(1);
print ord($byte)."\n";
$byte = $prng->getBytes(1);
print ord($byte)."\n";
```

> 118
> 118
> 118

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/seedspring/commit/540c66795b0f336f8325524d3c48c0112701a4e7

Thanks for reporting this bug. I should have used `ceil()` instead of `floor()`. Now it behaves as expected, and a unit test will catch any regressions in the future.

**Comment by proto-n** [comment]
Thanks for fixing it! I'm still curious though (for my own education), why is the nonce changed the way it is?

By the way, this is a very nice library, thanks for making it! I'm using it to generate deterministic random numbers in a use case where it is important to keep the determinism regardless of the underlying primitives or future php (or openssl) version changes. From what I gather, it looks like it would be a good fit for this purpose. What do you think about this?

(Sorry about asking here, I'm not sure what the correct medium would be to do so.)

**Comment by paragonie-scott** [comment]
It's an internals thing. AES has a block size of 16 bytes.

See [this test](https://github.com/paragonie/seedspring/blob/master/test/SeedSpringTest.php#L13-L20). Also [this](https://3v4l.org/0FGrD) (which tells me I got the byte order wrong).
