### ISSUE TITLE
PHP8 Support?

### ISSUE THREAD

**Issue by mateusrevoredo** [paragonie/seedspring#4]
Hello,

First of all, thanks for this great library. 

I recently noticed that master contains some changes that have not been tagged yet, including the changes on [composer.json#L18](https://github.com/paragonie/seedspring/commit/2a7da7a26abec353b5c236f29204c7151ebd4224#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R18), which removes the restriction from PHP `^5.6.0|^7.0.0` and replaces with `>= 5.6`. Therefore, making it compatible with PHP8 and PHP8.1.

Would it be possible for you to release a new `1.2.0` tag containing this changes? 

Thank you in advance for your consideration

**Comment by paragonie-security** [comment]
We weren't aware that anyone was using this for anything important, so it simply hadn't been a priority.

Happy to cut a 1.2.0 release though.

**Comment by paragonie-security** [comment]
https://github.com/paragonie/seedspring/releases/tag/v1.2.0

**Comment by mateusrevoredo** [comment]
Thank you for considering my request. I bet there are more people out there who would also benefit from this change. 

Best.
